### ISSUE TITLE
Replace language-specific metadata fields with hash

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-traject#139]
Some metadata fields ('agg_data_provider_ar',  'agg_data_provider_country_ar',  'agg_provider_ar',  'agg_provider_country_ar') have the language value recorded in the name of the field. These should be replaced with a hash value as used in https://github.com/sul-dlss/dlme-transform/pull/240 and https://github.com/sul-dlss/dlme-traject/pull/138). 

Requirements:
- [x] remove any fields that end in '_ar' from the validation schema (this may be accomplished when the PRs reference above get merged)
- [x] for each config file that has 'agg_data_provider_ar', etc. replace with the new method

This should not effect `metadata_mappings.json` or the methods used to retrieve those values, only the IR validation and the configs.

**Comment by mjgiarlo** [comment]
@jacobthill Can you unpack 
> for each config file that has 'agg_data_provider_ar', etc. replace with the new method
:question:

**Comment by jacobthill** [comment]
e.g. replace ```to_field 'agg_data_provider_ar', data_provider_ar``` with ```to_field 'agg_data_provider', data_provider_ar, lang('ar-Arab')``` and pass 'agg_data_provider' as an argument to ```each_record convert_to_language_hash```.  Repeat with all four fields that end in '_ar' (they should be at the bottom of each config under the comment `# Arabic Agg`. If I understand your implementation correctly I think that is what is required. Does that make sense?

**Comment by mjgiarlo** [comment]
@jacobthill :100: clear; I was being obtuse. :smiley: 

I can make that change unless you would prefer to do it. What do you think?

**Comment by jacobthill** [comment]
If you have time, that would be helpful. Thank you

**Comment by mjgiarlo** [comment]
> If you have time, that would be helpful. Thank you

will do!

**Comment by mjgiarlo** [comment]
@jacobthill ok, all the changes to test this out are now in the `master` branches of dlme-traject and dlme-transform. Ready for testing tomorrow.
