### ISSUE TITLE
bnf_cealex_config is producing invalid IR.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dlme-traject#3]
https://github.com/sul-dlss/dlme-traject/blob/master/bnf_cealex_config.rb#L42

`agg_is_shown_at` should be a hash with `wr_id` as a value

**Comment by peetucket** [comment]
> `agg_is_shown_at` should be a hash with `wr_id` as a value

can we use this as an example of how it should be produced: https://github.com/sul-dlss/dlme-traject/blob/master/penn_near_east_config.rb#L49-L60

**Comment by jcoyne** [comment]
@peetucket that seems to be the correct way.

**Comment by peetucket** [comment]
> @peetucket that seems to be the correct way.

Cool, PR here: #4
