### ISSUE TITLE
Harvard maps are missing links

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme-traject#41]
We don't have links for the Harvard maps. @waynegraham pulled many of these maps from OpenGeoMetadata/Earthworks, and since many of them are large GeoTIFFs, maybe we should just link to Earthworks?

**Comment by waynegraham** [comment]
This data was never scrutinized other than "this looks like it's in the region." I would be in favor of removing this collection (I don't think it's very many) until the data could be vetted and technical details for auto-harvesting can be worked through in a future work cycle.
