### ISSUE TITLE
Sakip Sabanci Museum items are missing agg_preview

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme-traject#59]
Create a lookup function for CONTENTdm thumbnails. Consider adding IIIF manifests, too?

**Comment by anarchivist** [comment]
The source data does not contain thumbnail URIs in it, so they need to be constructed by parsing data from the value we use to produce `agg_is_shown_at`. I believe we should be able to use the same code for the AUC data.

**Comment by jacobthill** [comment]
I will look into this. I'm also interested in added IIIF manifests if possible but will likely need some help. @peetucket is this something you would be able to help with?

**Comment by anarchivist** [comment]
I've got a branch for the thumbnail generation code (mostly because I could start from something we used to use at DPLA). I have not yet worked on the manifest link code.

**Comment by peetucket** [comment]
For context, this is the desire to generate IIIF manifests when harvesting content?

**Comment by anarchivist** [comment]
@peetucket CONTENTdm now provides IIIF manifests. Essentially, we need to construct the URIs to the manifests based upon data we already have.

**Comment by peetucket** [comment]
oh, i see, so its IIIF manifest URL generation based on identifiers and/or other bits of metadata we have in the harvested data, and then adding that URL to a field during the mapping?

**Comment by anarchivist** [comment]
Yes, exactly.

**Comment by peetucket** [comment]
Cool, do we have any example data with the incoming URIs and the IIIF manifest URI?  Also curious if we have an established IIIF manifest field name to map into.

**Comment by jacobthill** [comment]
Not sure exactly which fields we would need to map @peetucket but the info is here: https://github.com/sul-dlss/dlme/blob/master/docs/application_profile.md

**Comment by jacobthill** [comment]
On `dlme-transform` branch `cdm-thumbs` and `dlme-traject` branch `t59-ssm-thumbnail` running ```docker run --rm -e SKIP_FETCH_CONFIG=true                 -e SKIP_FETCH_DATA=true                 -v $(pwd)/.:/opt/traject                 -v $(pwd)/../dlme-traject:/opt/traject/config                 -v $(pwd)/../dlme-metadata:/opt/traject/data                 -v $(pwd)/output:/opt/traject/output                 suldlss/dlme-transform:latest                 sakip-sabanci``` results in the following error: ``` Exception: NoMethodError: undefined method `thumbnail' for #<Traject::Indexer:0x0000557dbc64e670>
    config/sakip_sabanci_config.rb:51:in `block (2 levels) in load_config_file'

[ERROR] undefined method `thumbnail' for #<Traject::Indexer:0x0000557dbc64e670>
config/sakip_sabanci_config.rb:51:in `block (2 levels) in load_config_file': undefined method `thumbnail' for #<Traject::Indexer:0x0000557dbc64e670> (NoMethodError)```

 I expect to be able to use pass the extracted dc:identifier value (e.g.  `extract_oai('dc:identifier[last()]'), strip)]`) to the `thumbnail` function in `dlme-transfrom/lib/macros/content_dm.rb` but I'm not sure how. It seemed like the problem was that I was trying to pass a Proc when `thumbnail` expected a string, but @anarchivist refactored the macro and I still get the same error. @justinlittman @jcoyne can one of you review https://github.com/sul-dlss/dlme-transform/pull/143 and if that looks good, suggest a way to pass `extract_oai('dc:identifier[last()]'), strip)]` or the equivalent to `thumbnail` that doesn't cause an error.

**Comment by anarchivist** [comment]
Note that the PR changes the method that you need to invoke in the mapping - you'll need to do something like this:

```ruby
to_field 'agg_preview', extract_cdm_preview
```

**Comment by jacobthill** [comment]
Thanks, let me try that

**Comment by jacobthill** [comment]
Ok with the context the same as the above except changing the way I call the new function in `dlme-traject/sakip-sabanci-config` to `to_field 'agg_preview', extract_cdm_preview` I get the following error:
```
2019-04-10T18:29:21+00:00  INFO    Traject::Indexer with 1 processing threads, reader: TrajectPlus::XmlReader and writer: DlmeJsonResourceWriter
[ERROR] undefined method `except' for #<String:0x0000557e1d8c4308>
/opt/traject/lib/adjust_cardinality.rb:72:in `process_node': undefined method `except' for #<String:0x0000557e1d8c4308> (NoMethodError)
```

**Comment by justinlittman** [comment]
Try
```
to_field 'agg_preview' do |_record, accumulator, context|
  accumulator << transform_values(
      context,
      'wr_id' => [extract_cdm_preview]
  )
end
```
