### ISSUE TITLE
Fix no agg_has_view error in marc_config

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-traject#65]
to_field 'agg_has_view' is grabbing the url from a marc field that is not consistently available in the raw data. An alternative approach would be to add the base url `http://hdl.library.upenn.edu/1017/d/medren/` and the first id value (which i believe is `extract_marc('001')`). I'm getting an error trying to add a string to a Proc.

**Comment by jcoyne** [comment]
@jacobthill can you provide an example of what you are doing?  What configs are you using, what environment, what error are you seeing?

**Comment by jacobthill** [comment]
I'm just running traject from docker with dlme-transform and dlme-traject on master. Pointing to the `penn/marc` files. This uses the marc_config. The error is: ```Transform produced invalid data. The errors are: {"agg_has_view"=>{0=>{"wr_id"=>["must be filled"]}}} The data looked like this: { "cho_identifier": [ "1469643", "155962434" ], "cho_title": [ "Dalāʼil al-khayrāt wa-shawāriq al-anwār fī dhikr al-ṣalāt ʻalā al-nabī al-mukhtār [manuscript]." ], "cho_contributor": [ "Camac, William,1829-1900,former owner." ], "cho_creator": [ "Jazūlī, Muḥammad ibn Sulaymān, d. 1465" ], "cho_date": [ "1422" ], "cho_description": [ "Prayers and litanies in praise of the Prophet. Important for Sunni Muslims. Includes a simple double-page image of Mecca (f. 15v-16r). Dalāʼil on ff.1-102; ff. 103ff. contain several shorter works.", "Page layout consists of a text block surrounded by a gold border, with many marginal notes.", "Foliated in two separate sections: ff. 1-161, 1-19.", "Extensive use of red ink for headings and for words and phrases of text. Red, gold, blue, white, orange and other colors used in a few places for headings and decoration.", "Last 19 leaves appear to be a separate section added later. They contain only text without gold border or marginalia.", "Many notes and comments on the endpapers.", "Manuscript in generally good condition. Some of the leaves are splitting at the edges, and many have been repaired and reinforced. Many leaves are water-stained, causing some smudging of the text in the affected areas.", "Binding and leather cover in good condition.", "This manuscript was examined by Professor Aḥmad Mahdavī Dāmghānī. His notes in Persian are on file in the Library.", "Translated into English as: Guide to happiness, a manual of prayer, trans. by J. B. Pearson; with a life of al-G [sic] by A. G. Ellis. Oxford, 1907." ], "cho_extent": [ "180 leaves" ], "cho_format": [ "Book", "Manuscript/Archive" ], "cho_has_type": [ "Mecca (Saudi Arabia)" ], "cho_medium": [ "paper, col. ill" ], "cho_spatial": [ "Mecca (Saudi Arabia)" ], "cho_subject": [ "Islam Prayers and devotions Early works to 1800.", "Prayer Islam Early works to 1800.", "Mecca (Saudi Arabia) Pictorial works." ], "id": "penn_1469643", "agg_data_provider": "University of Pennsylvania Libraries", "agg_provider": "University of Pennsylvania Libraries", "agg_has_view": [ { "wr_id": null } ] }```

**Comment by jcoyne** [comment]
@jacobthill Thank you.  It's very difficult for us to know how to diagnose and then fix a problem without details.  Please remember to provide as much detail as you can when you create a ticket, preferably with a way to reproduce the error.

**Comment by justinlittman** [comment]
> An alternative approach would be to add the base url http://hdl.library.upenn.edu/1017/d/medren/ and the first id value (which i believe is extract_marc('001')). I'm getting an error trying to add a string to a Proc.

Can you provide (1) the config that you are trying that produces the error; (2) the command that you are executing that produces the error for the smallest possible unit (e.g., a single record); (3) the expected result? Thanks!

**Comment by jacobthill** [comment]
@jcoyne Got it.

**Comment by jacobthill** [comment]
@justinlittman the config is the `marc_config.rb` file in dlme-traject. The command is ```docker run --rm -e SKIP_FETCH_CONFIG=true                 -e SKIP_FETCH_DATA=true                 -v $(pwd)/.:/opt/traject                 -v $(pwd)/../dlme-traject:/opt/traject/config                 -v $(pwd)/../dlme-metadata:/opt/traject/data                 -v $(pwd)/output:/opt/traject/output                 suldlss/dlme-transform:latest                 penn/marc```. The expected result is the error message posted above

**Comment by justinlittman** [comment]
Does something like this work?
```

**Comment by jacobthill** [comment]
That solves the problem I was encountering but the url pattern is not consistent. Is there a way to do this:
```
to_field 'agg_has_view' do |_record, accumulator, context|
  accumulator << transform_values(context, 'wr_id' => extract_marc('856u', first: true))
end
``` 
unless that returns an empty wr_id and, in that case, do:

```
to_field 'agg_has_view' do |_record, accumulator, context|
  accumulator << transform_values(context, 'wr_id' => [extract_marc('001', first: true), prepend('http://hdl.library.upenn.edu/1017/d/medren/')] )
end
``` 
?

**Comment by justinlittman** [comment]
Hmmm ...
```

**Comment by jacobthill** [comment]
That doesn't seem to catch the null wr_id.

**Comment by justinlittman** [comment]
Can you give me an example?

**Comment by jacobthill** [comment]
@justinlittman its exactly the same as above. What do you mean give an example? The context, the command I run, the error reported, are all the same as above. I think I'm not clear on what you need.

**Comment by jacobthill** [comment]
Maybe I should have just mentioned that the context was exactly the same as above?

**Comment by justinlittman** [comment]
```

**Comment by jacobthill** [comment]
Thanks @justinlittman
